### ISSUE TITLE
URL bug (Some classes not included in URL and end up in unselected state)

### ISSUE THREAD

**Issue by TobiasWooldridge** [TobiasWooldridge/UniBuddyTimetable#38]
http://timetable.unibuddy.com.au/?topics=31283(46192.7)_31746(46960.1_46959.3_46958.3)_32122(47519.1_47518.6)_32981(48855.3)

"The ECON1005 tutorial doesn't seem to want to stay, whenever I bookmark it and reload, that class disappears and I have to click it again to make it show on the course planner once more."

Reported by Alex L via email

**Comment by rdpeake** [comment]
Fixed in 1366b0eee14de3763925f7d3f743a7705f30a58f
